version: '2'

services:
  pipeline:
    image: gfw/pipe-nnet
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  gcloud:
    image: gfw/pipe-nnet
    build: .
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

volumes:
  gcp:


